version: '3.4'

# networks:
#   default:
#     driver: nat

services: 
  mongodb: 
    image: "mongo"
    ports: 
      - "27017:27017"
  sqldb: 
    image: "mcr.microsoft.com/mssql/server"
    ports: 
      - "1433:1433"
    environment: 
       ACCEPT_EULA: "Y"
       SA_PASSWORD: "Password@123"
  authservice:
    build:
      context: .
      dockerfile: KeepNoteAPIs\AuthenticationService\AuthenticationService\Dockerfile 
    depends_on: 
      - sqldb
    image: authservice
    restart: always
    # networks:
    #   - default
    environment: 
      SQLSERVER: "server=sqldb;database=AuthenticationDb;user id=sa;password=Password@123;"
    ports: 
      - "5003:80"
  categoryservice:
    build:
      context: .
      dockerfile: KeepNoteAPIs\CategoryService\CategoryService.API
    restart: always
    # networks:
    #   - default 
    depends_on: 
      - mongodb
    environment: 
      Mongo_DB: "mongodb://mongodb:27017"
    image: categoryservice
    ports: 
      - "5002:80"
  notesservice:
    build:
      context: .
      dockerfile: KeepNoteAPIs\NoteService\NoteService.API\Dockerfile
    restart: always
    # networks:
    #   - default 
    depends_on: 
      - mongodb
    environment: 
      Mongo_DB: "mongodb://mongodb:27017"
    image: notesservice
    ports: 
      - "5000:80"
  remindeservice:
    build:
      context: .
      dockerfile: KeepNoteAPIs\ReminderService\ReminderService.API
    restart: always
    # networks:
    #   - default 
    depends_on: 
      - mongodb
    environment: 
      Mongo_DB: "mongodb://mongodb:27017"
    image: remindeservice
    ports: 
      - "5004:80"
  keepnoteclientapp:
    build:
      context: .
      dockerfile: ClientApp\Dockerfile
    image: keepnoteclientapp
    restart: always
    # networks:
    #   - default
    depends_on:
      - notesservice
      - authservice
    ports:
      - "4200:4200"
  